# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Vivado/miniLA_basic_xzx_and_xwt/miniLA_basic_pipeline/src/rtl/ip/bram_axi/bram_axi.xci
# IP: The module: 'bram_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/miniLA_basic_xzx_and_xwt/miniLA_basic_pipeline/src/rtl/ip/bram_axi/bram_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_axi'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/Vivado/miniLA_basic_xzx_and_xwt/miniLA_basic_pipeline/src/rtl/ip/bram_axi/bram_axi.xci
# IP: The module: 'bram_axi' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Vivado/miniLA_basic_xzx_and_xwt/miniLA_basic_pipeline/src/rtl/ip/bram_axi/bram_axi_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'bram_axi'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
